stages:
  - build
  - deploy

#Продакшн-сборка
build_production:
  stage: build
  only: 
    - master
  tags:
    - gsdev
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
    - dist

#Деплой на прод
deploy_production:
  stage: deploy
  only: 
  - master
  tags:
   - gsdev
  script:
   - rm -Rf /home/agsdev/school/*
   - cp -Rf . /home/agsdev/school
   - cd /home/flexapp
   - npm install --progress=false
